# Generated by Django 6.1.1 on 2026-09-14 19:05

import attendance.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('range_m', models.PositiveIntegerField(help_text='Geofence radius in metres')),
                ('rotation_seconds', models.PositiveIntegerField(default=30, help_text='QR refresh window')),
                ('collect_name', models.BooleanField(default=True)),
                ('collect_id', models.BooleanField(default=True)),
                ('id_label', models.CharField(default='ID / UG number', max_length=40)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('code_secret', models.CharField(default=attendance.utils.generate_code_secret, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('id_number', models.CharField(blank=True, default='', max_length=40)),
                ('captured_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('captured_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('present', 'Present'), ('rejected', 'Rejected')], default='present', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'attendee')},
            },
        ),
    ]
